/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnitest_luyanhao_normal_ndk_build_JniTest */

#ifndef _Included_com_jnitest_luyanhao_normal_ndk_build_JniTest
#define _Included_com_jnitest_luyanhao_normal_ndk_build_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_luyanhao_normal_ndk_build_JniTest
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnitest_luyanhao_normal_1ndk_1build_JniTest_getPackname
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
